POST http://localhost:3003/api/blogs HTTP/2
content-type: application/json

{
    "title": "Govt to incubate 'Aatmanirbhar' web browsers that compete with Google Chrome, Mozilla Firefox",
    "author": "DEEPSEKHAR CHOUDHURY",
    "url": "https://www.moneycontrol.com/news/business/govt-to-incubate-aatmanirbharta-web-browsers-that-compete-with-google-chrome-mozilla-firefox-11134911.html",
    "likes": 0
}
