POST http://localhost:3001/api/login HTTP/2
content-type: application/json

{
    "username": "Kushagra0304",
    "password": "KUsh1234"
}

###
POST http://localhost:3001/api/users HTTP/2
content-type: application/json

{
    "name": "Kushagra",
    "username": "Kushagra0304",
    "password": "KUsh1234"
}